### ISSUE TITLE
uninitialized constant FileUtils

### ISSUE THREAD

**Issue by wbkboyer** [alexivkin/Jekyll-Art-Gallery-Plugin#1]
Hi! I am attempting to follow your guide for using your plugin, but came across the following error:

`wbkboyer@Apollo ~/GitHub/wandaboyer.github.io/_plugins $ ruby jekyll-art-gallery-generator.rb 
jekyll-art-gallery-generator.rb:8:in`<main>': uninitialized constant FileUtils (NameError)
Did you mean?  FileTest
`

When I require fileutils rather than include FileUtils, I get the following error:
`wbkboyer@Apollo ~/GitHub/wandaboyer.github.io/_plugins $ ruby jekyll-art-gallery-generator.rb 
jekyll-art-gallery-generator.rb:13:in`module:Jekyll': uninitialized constant Jekyll::StaticFile (NameError)
Did you mean?  StaticGravity
    from jekyll-art-gallery-generator.rb:13:in `<main>'
`
However, from what [I have seen](http://stackoverflow.com/questions/318144/what-is-the-difference-between-include-and-require-in-ruby), you want to extend the StaticFile class to the GalleryFile class, so include is the correct statement to use... I'm therefore stuck trying to figure out how to tell Ruby where these resources are! :(

I'm running Ruby 2.3.0 and Jekyll 3.1.6... Also, would you be willing to list the requirements for this Ruby plugin in the .md file? Thanks so much for your time, and for creating this plugin!

p.s. I found [this link](http://guides.rubygems.org/make-your-own-gem/) for how to make your own gems... I'd do it, but I'm not sure what information to use in the gemspec...

**Comment by wbkboyer** [comment]
Also, I took a look around and found the [Jekyll static_file.rb](https://github.com/jekyll/jekyll/blob/master/lib/jekyll/static_file.rb), but including nor requring seems to work... Thanks again!!

**Comment by alexivkin** [comment]
Wanda, the plugin is intended to be run by Jekyll itself when it builds your site, not to be run directly. To have Jekyll run it put it into _plugins. 
It's not built as a gem, but the prerequisites are listed in the README.

**Comment by wbkboyer** [comment]
Ah, I suppose I'm trying to use it to generate the static page for use on my github pages, since pages automatically disables plugins :(

Would you happen to have advice on how to do this? I'd be truly thankful for your help! I installed the prerequisites as given in the readme, and have the aforementioned versions of ruby and Jekyll,  so I'm not sure if I'm missing something else...

**Comment by alexivkin** [comment]
The plugin uses Jekyll's data and libraries and will only run when called by Jekyll's plugin framework. You need to use a local installation of Jekyll with the plugin to generate the static version of your website. Then you can upload your generated static gallery pages for GitHub Pages to serve. There is no other way until GitHub enables support for the plugins on GitHub Pages.
I doubt they ever do it for third party plugins will though - there is too much potential security and performance abuse risk

**Comment by wbkboyer** [comment]
Brilliant!! Thank you so much for your help... I'll putter around with this, taking the steps that you've advised... I think I can figure out how to get Jekyll to run the script now that I know what I should look for... have a great weekend!
