### ISSUE TITLE
Cannot load such file -- jekyll-art-gallery-generator

### ISSUE THREAD

**Issue by bartek-szymanski** [alexivkin/Jekyll-Art-Gallery-Plugin#2]
I have configured it as in the README, but I get 

`Dependency Error: Yikes! It looks like you don't have jekyll-art-gallery-generator or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-art-gallery-generator' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! `

**Comment by alexivkin** [comment]
Hmm...double check that it's installed correctly and in the right folder for jekyll to find it
